version: '3'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_USER: tasks_management
      POSTGRES_DB: tasks_management
